# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cbd77f6f35119fae3c617c31b8de0bc70ee3849b9858dbcb5b97510db30f755cea2a4118d815965e1ffcb1c47abe1450651a7804854659b526c8ca00a61cefc

test:
  secret_key_base: 5800d4692d749f6cc1cbbf93f20b478ae59e889cac42d3a2a1e714a5f1c39da3daced5521e4521b32959af1d3f57a101f9d3fd04dbc9579c8a728ef33db73c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
